In [1]:
import pandas as pd
import sqlite3

# Loading Raw ACS Data into a DataFrame

In [2]:
df = pd.read_csv("../data/acsh_raw.csv")

# Exploratory Data Analysis

Using a Custom Function from the Utilities Notebook

In [3]:
from utilities import basic_eda

basic_eda(df)

DataFrame Shape: (22482, 2)

 Column Names:
['SERIALNO', 'TYPEHUGQ']

 Data Types:
SERIALNO    object
TYPEHUGQ     int64
dtype: object

 DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22482 entries, 0 to 22481
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   SERIALNO  22482 non-null  object
 1   TYPEHUGQ  22482 non-null  int64
dtypes: int64(1), object(1)
memory usage: 351.4+ KB

 Null Values (%):
Series([], dtype: float64)

 Preview (Head):
        SERIALNO  TYPEHUGQ
0  2022GQ0000029         2
1  2022GQ0000118         2
2  2022GQ0000184         3
3  2022GQ0000384         3
4  2022GQ0000396         2

 Preview (Tail):
            SERIALNO  TYPEHUGQ
22477  2022HU1446190         1
22478  2022HU1446229         1
22479  2022HU1446233         1
22480  2022HU1446259         1
22481  2022HU1446392         1

# Cleaning

## Column Names

Using the data dictionary provided for this dataset, I will start by changing column names to descriptive ones.

In [4]:
df = df.rename(columns={"SERIALNO": "serial_number","TYPEHUGQ": "group_quarters_type"})

df.head()

   serial_number  group_quarters_type
0  2022GQ0000029                    2
1  2022GQ0000118                    2
2  2022GQ0000184                    3
3  2022GQ0000384                    3
4  2022GQ0000396                    2

## Mapping Coded Values
Using ACS Data Dictionary

This section converts coded values into descriptive labels.

In [5]:
group_quarters_map = {
    1: "Housing unit",
    2: "Institutional group quarters",
    3: "Noninstitutional group quarters"
}

df["group_quarters_type"] = df["group_quarters_type"].map(group_quarters_map)

df.head()

   serial_number              group_quarters_type
0  2022GQ0000029     Institutional group quarters
1  2022GQ0000118     Institutional group quarters
2  2022GQ0000184  Noninstitutional group quarters
3  2022GQ0000384  Noninstitutional group quarters
4  2022GQ0000396     Institutional group quarters

## Rechecking Data Types

In [6]:
df.dtypes

serial_number          object
group_quarters_type    object
dtype: object

# Converting to SQLite Database Table

In [ ]:
# Connect to existing SQLite database
conn = sqlite3.connect("../data/cleaned_data.sqlite")

# Write the DataFrame `df` to the database as a new table called "acsh_data"
df.to_sql(
    name="acsh_data",       # name of the new table
    con=conn,               # database connection
    if_exists="replace",    # overwrite if table already exists
    index=False             # don't include the index as a column
)

# Close the connection
conn.close()

print("Table 'acsh_data' successfully added to cleaned_data.sqlite.")

Table 'acsh_data' successfully added to cleaned_data.sqlite.